FROM node:20.6

WORKDIR /app

COPY src/workers/package.json /app/package.json
RUN npm install && npm cache clean --force

COPY dist/workers /app/workers
COPY src/services /app/services

CMD ["node", "/app/workers/worker.js"]
